#
# PLEASE RELOAD OR RESTART SERVER AFTER A CHANGE IN THIS FILE.
# More information on plugin page : https://dev.bukkit.org/projects/spawnersilk
# Any trouble to use this file ? Ask help on Discord : https://discordapp.com/invite/jCsvJxS
#
# auto-update
#   true  : New update will be downloaded and installed automatically
#   false : You need to download and install update by yourself
#
# need-silk-touch
#   true  : Only player with silkTouch can drop spawner
#   false : Everybody can drop spawner
#
# pickaxe-mode
#   0 : Player can get spawner by breaking it no matter how
#   1 : Player need to break the spawner with wooden pickaxe or better
#   2 : Player need to break the spawner with stone pickaxe or better
#   3 : Player need to break the spawner with iron pickaxe or better
#   4 : Player need to break the spawner with golden pickaxe or better
#   5 : Player need to break the spawner with diamond pickaxe or better
#   6 : Player need to break the spawner with netherite pickaxe
#
# drop-mode
#   0 : Spawner of the creature is dropped
#   1 : Basic spawner is dropped with egg of the creature type (depends on drop-egg-chance)
#
# drop-chance
#   Percentage of chance that player drop a spawner by mining it
#
# drop-egg-chance
#   Percentage of chance that player drop an egg (only for drop-mode = 1)
#
# explosion-drop-chance
#   Percentage of chance that player drop a spawner by an explosion
#
# spawners-can-be-modified-by-egg
#   true  : player can change the spawner type with eggs
#   false : Spawner type is locked
#
# drop-to-inventory
#   true : Spawner go directly to inventory
#   false : Naturally drop the spawner
#
# use-egg
#   true : egg is consume on the spawner
#   false : egg is not consume on the spawner
#
# drop-in-creative
#   true : spawner drops on creative mode
#   false : spawner don't drops on creative mode
#
# spawners-generate-xp
#   true : xp drops when mining spawner (warning : risk of xp farming !)
#   false :xp don't drops when mining spawner
#

auto-update: true
need-silk-touch: true
pickaxe-mode: 5
drop-chance: 100
drop-egg-chance: 100
drop-mode: 0
explosion-drop-chance: 10
spawners-can-be-modified-by-egg: true
drop-to-inventory: false
use-egg: true
drop-in-creative: false
spawners-generate-xp: false




