################################################################################################################################
# Welcome to the SpawnerSilk configuration file!                                                                               #
#                                                                                                                              #
# You can find more information about the plugin and this file on the plugin page:                                             #
#   > https://dev.bukkit.org/projects/spawnersilk                                                                              #
# If you need any support, feel free to ask for it on our Discord server:                                                      #
#   > https://discordapp.com/invite/jCsvJxS                                                                                    #
#                                                                                                                              #
# If you make any changes in this file, please run the command '/sps reload' to apply the changes!                             #
################################################################################################################################

# true  : New update will be downloaded and installed automatically
# false : You need to download and install update by yourself
auto-update: true

# true  : Only player with silkTouch can destroy spawner (need spawnersilk.minespawner permission)
# false : Everybody can destroy spawner
need-silk-touch-to-destroy: false

# true  : Only player with silkTouch can drop spawner (need spawnersilk.minespawner permission)
# false : Everybody can drop spawner
need-silk-touch: true

# 0 : Player can get spawner by breaking it no matter how
# 1 : Player need to break the spawner with wooden pickaxe or better
# 2 : Player need to break the spawner with stone pickaxe or better
# 3 : Player need to break the spawner with iron pickaxe or better
# 4 : Player need to break the spawner with golden pickaxe or better
# 5 : Player need to break the spawner with diamond pickaxe or better
# 6 : Player need to break the spawner with netherite pickaxe
pickaxe-mode: 5

# 0 : Spawner of the creature is dropped
# 1 : Basic spawner is dropped with egg of the creature type (depends on drop-egg-chance)
drop-mode: 0


# Percentage of chance that player drop a spawner by mining it
drop-chance: 100

# Percentage of chance that player drop an egg (only for drop-mode = 1)
drop-egg-chance: 100

# Percentage of chance that player drop a spawner by an explosion
explosion-drop-chance: 10

# true  : player can change the spawner type with eggs
# false : Spawner type is locked
spawners-can-be-modified-by-egg: true

# true  : Spawner go directly to inventory
# false : Naturally drop the spawner
drop-to-inventory: false

# true : egg is consume on the spawner
# false : egg is not consume on the spawner
use-egg: true

# true : spawner drops on creative mode
# false : spawner don't drop on creative mode
drop-in-creative: false

# true : xp drops when mining spawner (warning : risk of xp farming !)
# false :xp don't drop when mining spawner
spawners-generate-xp: false

# true : enable spawner overlay to see spawner detail when looking at it (need also spawnersilk.overlay perms)
# false : disable spawner overlay
spawner-overlay: true

# Time in seconds before the overlay disappears
# A time less than 3s is not recommended
spawner-overlay-delay: 10

# You can put spawners that you don't want droppable in this list. The name is the entity name in uppercase (ex BEE).
# In case of space in the name just put an _ (ex : ZOMBIE_HORSE)
black-list:
  - 'BOAT_SPAWNER'

















